# Generated by Django 4.2 on 2024-04-14 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='modifier',
            new_name='default_modifier',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='modifier_amount',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weight',
        ),
        migrations.AddField(
            model_name='exercise',
            name='default_reps',
            field=models.PositiveIntegerField(default=8, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='exercise',
            name='default_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(1500), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='workout',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='five_rep_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(1500), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='ExerciseSet',
        ),
    ]
