# Generated by Django 4.2 on 2024-04-08 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0002_remove_routinesettings_workout_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_update_five_rep_max', models.BooleanField(default=False)),
                ('show_rest_timer', models.BooleanField(default=False)),
                ('show_workout_timer', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Workout Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='routinesettings',
            options={'verbose_name_plural': 'Routine Settings'},
        ),
        migrations.DeleteModel(
            name='CardioLog',
        ),
    ]
