# Generated by Django 4.2 on 2024-03-01 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0002_alter_workoutset_reps"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="five_rep_max",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                validators=[
                    django.core.validators.MaxValueValidator(1500),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
