# Generated by Django 4.2 on 2024-03-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0003_exercise_five_rep_max"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="exercises",
            field=models.ManyToManyField(to="workout.exercise"),
        ),
    ]
