# Generated by Django 4.2 on 2024-03-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0006_alter_workout_exercises"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutlog",
            name="total_time",
            field=models.IntegerField(default=0),
        ),
    ]
