# Generated by Django 4.2 on 2024-03-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0007_workoutlog_total_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workoutlog",
            old_name="workout",
            new_name="workout_name",
        ),
    ]
