# Generated by Django 4.2 on 2024-03-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0008_rename_workout_workoutlog_workout_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workoutlog",
            old_name="workout_name",
            new_name="workout",
        ),
    ]
