# Generated by Django 4.2 on 2024-03-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_rename_workout_name_workoutlog_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='default_modifier',
            field=models.CharField(choices=[('add', 'Add'), ('subtract', 'Subtract'), ('percentage', 'Percentage'), ('exact', 'Exact')], default='percentage', max_length=20),
        ),
    ]
