# Generated by Django 5.0.2 on 2024-03-24 04:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0012_cardiolog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardiolog",
            name="duration_hours",
        ),
        migrations.RemoveField(
            model_name="cardiolog",
            name="duration_minutes",
        ),
        migrations.RemoveField(
            model_name="cardiolog",
            name="duration_seconds",
        ),
        migrations.RemoveField(
            model_name="cardiolog",
            name="time",
        ),
        migrations.AddField(
            model_name="cardiolog",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
        migrations.AddField(
            model_name="cardiolog",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cardiolog",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
