# Generated by Django 5.0.2 on 2024-03-24 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0013_remove_cardiolog_duration_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardiolog",
            name="distance",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99.99),
                ]
            ),
        ),
    ]
