# Generated by Django 4.2 on 2024-02-29 04:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_weightlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="height",
        ),
        migrations.RemoveField(
            model_name="user",
            name="weight",
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_of_measurement",
                    models.CharField(
                        choices=[("Imperial", "Imperial"), ("Metric", "Metric")],
                        default="Imperial",
                        max_length=8,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        default=70,
                        validators=[
                            django.core.validators.MinValueValidator(20.0),
                            django.core.validators.MaxValueValidator(120.0),
                        ],
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=160,
                        validators=[
                            django.core.validators.MinValueValidator(50.0),
                            django.core.validators.MaxValueValidator(1000.0),
                        ],
                    ),
                ),
                (
                    "bodyfat",
                    models.FloatField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(5.0),
                            django.core.validators.MaxValueValidator(60.0),
                        ],
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
