# Generated by Django 4.2 on 2024-04-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_userbodycompositionsetting_usersettings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutSetting',
        ),
    ]
