# Generated by Django 4.2 on 2024-02-29 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userbodycompositionsettings_weightlog_bodyfat_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserBodyCompositionSettings",
            new_name="UserBodyCompositionSetting",
        ),
    ]
