# Generated by Django 4.2 on 2024-03-02 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_userbodycompositionsettings_userbodycompositionsetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_update_five_rep_max", models.BooleanField(default=False)),
                ("show_rest_timer", models.BooleanField(default=False)),
                ("show_workout_timer", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
