# Generated by Django 4.2 on 2024-03-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_workoutsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightlog',
            old_name='bodyfat',
            new_name='body_fat',
        ),
        migrations.RenameField(
            model_name='weightlog',
            old_name='weight',
            new_name='body_weight',
        ),
    ]
