# Generated by Django 4.2 on 2024-03-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_bodyfat_weightlog_body_fat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbodycompositionsetting',
            old_name='bodyfat',
            new_name='body_fat',
        ),
        migrations.RenameField(
            model_name='userbodycompositionsetting',
            old_name='weight',
            new_name='body_weight',
        ),
    ]
