# Generated by Django 5.0.2 on 2024-03-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_rename_bodyfat_userbodycompositionsetting_body_fat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userbodycompositionsetting",
            old_name="unit_of_measurement",
            new_name="system_of_measurement",
        ),
    ]
