# Generated by Django 4.2 on 2024-04-13 18:15

import datetime
from django.db import migrations, models
import log.validators


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), validators=[log.validators.validate_duration_min, log.validators.validate_duration_max]),
        ),
    ]
