# Generated by Django 4.2 on 2024-04-19 05:16

from django.db import migrations, models
import django.utils.timezone
import log.validators


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutlog",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[
                    log.validators.validate_not_future_date,
                    log.validators.validate_not_more_than_5_years_ago,
                ],
            ),
        ),
    ]
