# Generated by Django 4.2 on 2024-04-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0003_alter_workoutlog_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="calories",
            field=models.PositiveIntegerField(),
        ),
    ]
