# Generated by Django 4.2 on 2024-04-19 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0004_alter_fooditem_calories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="carbs",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999.99),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="fat",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999.99),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="protein",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999.99),
                ]
            ),
        ),
    ]
