# Generated by Django 4.2 on 2024-04-14 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlogentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='nutrition_tracker.foodlogentry'),
        ),
        migrations.AlterUniqueTogether(
            name='foodlogentry',
            unique_together={('user', 'date')},
        ),
    ]
