# Generated by Django 4.2 on 2024-04-19 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition_tracker", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="foodlogentry",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="foodlogentry",
            name="user",
        ),
        migrations.DeleteModel(
            name="FoodItem",
        ),
        migrations.DeleteModel(
            name="FoodLogEntry",
        ),
    ]
